language: java
jdk:
  - oraclejdk8
sudo: false
install:
    mvn install -DskipTests=true -Dmaven.javadoc.skip=true -Dorg.bedework.deployment.properties=.travis.deploy.properties -Dorg.bedework.deploy.checkonly=true -B -V
